export const GET_DRIVERS = "GET_DRIVERS";
export const SEARCH_DRIVERS_SUCCESS = "SEARCH_DRIVERS_SUCCESS";
export const ORDER = " ORDER";
export const ORDENBYDOB = "ORDENBYDOB";
export const ORDENBYID = "ORDENBYID";
export const GET_TEAMS = "GET_TEAMS";
export const GET_ALL_API_BD = "GET_ALL_API_BD";
export const FILTERTEAMS = "FILTERTEAMS";
export const POSTDRIVERS = "POSTDRIVERS";
